# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: '3.8'
services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      LLM_MODEL_ID: ${LLM_MODEL_ID}

  tgi-server:
    image: ghcr.io/huggingface/text-generation-inference:2.4.0-intel-cpu
    container_name: tgi-server
    restart: unless-stopped
    ports:
      - ${TGI_PORT:-8080}:80
    volumes:
      - "${DATA_PATH:-./data}:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGING_FACE_TOKEN}
      MAX_INPUT_TOKENS: ${MAX_INPUT_TOKENS:-2048}
      MAX_TOTAL_TOKENS: ${MAX_TOTAL_TOKENS:-4096}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 100
    command: --model-id ${SAFETY_GUARD_MODEL_ID} --cuda-graphs 0

  guardrails-service:
    image: opea/guardrails:latest
    container_name: guardrails-service
    ports:
      - ${GUARDRAILS_PORT:-9090}:9090
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
      SAFETY_GUARD_ENDPOINT: ${SAFETY_GUARD_ENDPOINT}
      GUARDRAILS_COMPONENT_NAME: ${GUARDRAILS_COMPONENT_NAME}
    depends_on:
      - tgi-server

  mega-service:
    build:
      context: ./mega-service
      dockerfile: Dockerfile
    container_name: mega-service
    ports:
      - "8000:8000"
    environment:
      LLM_SERVICE_HOST_IP: ollama-server
      LLM_SERVICE_PORT: 11434
      GUARDRAILS_SERVICE_HOST_IP: guardrails-service
      GUARDRAILS_PORT: 9090
      SAFETY_GUARD_ENDPOINT: ${SAFETY_GUARD_ENDPOINT}
      host_ip: ${host_ip}
      LLM_ENDPOINT_PORT: ${LLM_ENDPOINT_PORT}
    depends_on:
      - ollama-server
      - guardrails-service

networks:
  default:
    name: opea-network
